=== hyeonn/XML_Report2/Vehicle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:target="http://www.example.com/Vehicle" targetNamespace="http://www.example.com/Vehicle" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<complexType name="DriveTrainType">
		<sequence>
			<element name="Engine" type="string"/>
			<element name="Transmission" type="string"/>
		</sequence>
	</complexType>
	<complexType name="VehicleType">
		<sequence>
			<element name="Body" type="string"/>
			<element name="DriveTrain" type="string"/>
		</sequence>
	</complexType>
	<complexType name="AutomobileType">
		<complexContent>
			<extension base="target:VehicleType">
				<sequence>
					<element name="Trunk" type="string"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="SedanType">
		<complexContent>
			<extension base="target:AutomobileType"/>
		</complexContent>
	</complexType>
	<complexType name="ConvertibleType">
		<complexContent>
			<extension base="target:AutomobileType">
				<sequence>
					<element name="OperatingRoof" type="string"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="TruckTupe">
		<complexContent>
			<extension base="target:VehicleType">
				<sequence>
					<element name="Compartment" type="string"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<element name="Vehicle">
		<complexType>
			<sequence>
				<element name="Automobile" type="target:AutomobileType"/>
				<element name="Sedan" type="target:SedanType"/>
				<element name="Convertible" type="target:ConvertibleType"/>
				<element name="Truck" type="target:TruckTupe"/>
			</sequence>
		</complexType>
	</element>
	<element name="Vehicles">
		<complexType>
			<sequence>
				<element ref="target:Vehicle" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
</schema>

=== hyeonn/XML_Report2/Vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vehicles xmlns="http://www.example.com/Vehicle" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.com/Vehicle ../../../../Desktop/20171688-%EC%9E%84%EC%9D%B4%ED%98%84/Vehicle.xsd">
	<Vehicle>
		<Automobile>
			<Body>ehyeonAutomobile</Body>
			<DriveTrain>ehyeonAutomobileDriveTrain</DriveTrain>
			<Trunk>ehyeonAutomobileTrunk</Trunk>
		</Automobile>
		<Sedan>
			<Body>ehyeonSedan</Body>
			<DriveTrain>ehyeonSedanDriveTrain</DriveTrain>
			<Trunk>ehyeonSedanTrunk</Trunk>
		</Sedan>
		<Convertible>
			<Body>ehyeonConvertible</Body>
			<DriveTrain>ehyeonConvertibleDriveTrain</DriveTrain>
			<Trunk>ehyeonConvertibleTrunk</Trunk>
			<OperatingRoof>ehyeonConvertibleOperatingRoof</OperatingRoof>
		</Convertible>
		<Truck>
			<Body>ehyeonTruck</Body>
			<DriveTrain>ehyeonTruckDriveTrain</DriveTrain>
			<Compartment>ehyeonTruckCompartment</Compartment>
		</Truck>
	</Vehicle>
</Vehicles>
